### PR TITLE
[pundle-cli] Add commands init and build

### PR DESCRIPTION
**Pull request by natew**

### CODE REVIEW

**Comment by natew** [comment]
It's not perfectly safe, it won't check for existing stuff.

**Comment by natew** [comment]
Added build command as well, documentation coming.

**Comment by natew** [comment]
Ok, don't want to go too far into this before getting approval. If this get merged, I can go ahead and write out some more docs.

Still pro renaming `motion` to `pundle-app` in the future.

**Comment by steelbrain** [comment]
I am in favor of renaming `motion` to `pundle-app`, also the PR mostly looks good to me but can you revert the changes to `package-lock.json`? It appears you are not on the latest version of Node.js so it's modifying package-lock to match old schema

**Comment by natew** [comment]
I'm on node 8.2.1 and npm 5.3.0 which I think are the latest versions. Re-ran bootstrap with no diff on the package-lock.json files.

**Comment by natew** [comment]
Ok that should revert 👍

**Comment by steelbrain** [comment]
Thank You

**Pull request merged**
