### PR TITLE
:memo: Update README links for v2

### PR DESCRIPTION
**Pull request by appsforartists**

### CODE REVIEW

**Comment by appsforartists** [comment]
There's no preset for Babel.  Should there be?

**Comment by steelbrain** [comment]
Oh about Babel preset, I didn't add it on purpose, mainly because there's only one package required to run it and users can just do `components: [require.resolve('pundle-transformer-babel')]`, but if you think that adding a preset is still a good thing I won't mind it

**Comment by appsforartists** [comment]
It's less about the preset and more about having somewhere to link to for documentation.  Should we just link to the Babel Transformer, with docs in that README about how to use it?

**Comment by steelbrain** [comment]
I'm working on a rewrite of the docs entirely in a separate PR. The docs in that PR have two sections, technical and introductory. Introductory tells what a preset or a component is and how to specify their configs, technical tells you how to write one etc.

The new main README will not have a lot of docs but rather a link to the docs site. The docs site will have a guide section which covers babel and typescript. Let me know what you think.

**Comment by appsforartists** [comment]
Excellent!

**Pull request merged**
