### PR TITLE
docs(getting-started): pundle init -> pundle new

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Comment by steelbrain** [comment]
Good eye, Thanks for the fix!

**Comment by Haroenv** [comment]
I also noticed that the help says

```
   new    [name],[type]    Copy default Pundle configuration into new directory (type can be full or basic, defaults to basic) 
```

but type is required

**Comment by steelbrain** [comment]
Type doesn't look like it's required

screen shot 2017-08-04 at 4 16 56 pm

Furthermore the syntax of the commands is `<something>` is required while `[something]` is optional

**Comment by Haroenv** [comment]
got it!

**Pull request merged**
